server:
  port: 10001
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:192.168.88.129}:${DB_PORT:3306}/${DB_DATABASE:bpo_esbmp}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useLegacyDatetimeCode=false&useTimezone=true&serverTimezone=Asia/Shanghai
    username: ${DB_USER:root}
    password: ${DB_PSWD:123456}

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      initialSize: 10
      maxActive: 100
      maxWait: 60000
      minIdle: 10
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      use-global-data-source-stat: true
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      username: ${DRUID_USER:root}
      password: ${DRUID_PSWD:123456}
      reset-stat-enable: ${DRUID_RESET_ENABLE:false}
# 配置spring cloud 服务发现
eureka:
  instance:
    prefer-ip-address: ${INSTANCE_PREFER:true}
  client:
    serviceUrl:
      # docker 部署开启
      defaultZone: http://admin:123@127.0.0.1:7001/eureka/